icon: snap/gui/markdown-editor.png
summary: Markdown Editor is a lightweight and intuitive app for creating and editing .md files with ease
group: Applications/Utility
vendor: adeeteya
packager: Aditya R
packagerEmail: adeeteya@gmail.com
license: MIT
url: https://github.com/adeeteya/FlutterMarkdownEditor

display_name: Markdown Editor

keywords:
  - Readme
  - Text
  - Markdown
  - Editor
  - Utility

generic_name: Markdown Editor
categories:
  - Utility

startup_notify: true