name: markdown-editor
version: 2.0.0
summary: Markdown Editor is an app for creating and editing .md files with ease.
description: Markdown Editor is a lightweight and intuitive app for creating and editing .md files with ease.
icon: snap/gui/markdown-editor.png
contact: mailto:adeeteya@gmail.com
source-code: https://github.com/adeeteya/FlutterMarkdownEditor
issues: https://github.com/adeeteya/FlutterMarkdownEditor/issues
license: MIT

confinement: strict
base: core22
grade: stable

slots:
  markdown-editor:
    interface: dbus
    bus: session
    name: com.adeeteya.markdown_editor

apps:
  markdown-editor:
    command: markdown_editor
    extensions: [gnome]
    plugs:
      - network
      - desktop
      - home
    slots:
      - markdown-editor
parts:
  markdown-editor:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart